// src/pages/TestControlFases.jsx
import ControlFasesTable from '../components/ControlFasesTable';

export default function TestControlFases() {
  const areas = [
  {
    id: '1',
    nombre: 'Matemáticas',
    nivel: 'Primer Nivel', 
    faseActual: 'Final',
    progreso: 100,
    clasificados: 12,
    noClasificados: 8,
    descalificados: 2,
    responsable: 'MG María González',
    estado: 'Concluido',
  },
  {
    id: '2',
    nombre: 'Física',
    nivel: '3ro Secundaria',
    faseActual: 'Clasificatorio',
    progreso: 75,
    clasificados: 18,
    noClasificados: 5,
    descalificados: 1,
    responsable: 'CQ Carlos Quispe',
    estado: 'En evaluación',
  },
  {
    id: '3',
    nombre: 'Química',
    faseActual: 'Final',
    progreso: 100,
    clasificados: 15,
    noClasificados: 10,
    descalificados: 3,
    responsable: 'AR Ana Rodríguez',
    estado: 'Confirmado',
  },
  {
    id: '4',
    nombre: 'Biología',
    nivel: '5to Primaria', 
    faseActual: 'Clasificatorio',
    progreso: 60,
    clasificados: 10,
    noClasificados: 12,
    descalificados: 0,
    responsable: 'LM Luis Mamani',
    estado: 'En evaluación',
  },
  {
    id: '5',
    nombre: 'Informática',
    nivel: 'Puma',
    faseActual: 'Final',
    progreso: 85,
    clasificados: 8,
    noClasificados: 6,
    descalificados: 1,
    responsable: 'PT Pedro Torrez',
    estado: 'Concluido',
  },
  {
    id: '6',
    nombre: 'Astronomía-Astrofísica',
    nivel: '4to Primaria',
    faseActual: 'Clasificatorio',
    progreso: 45,
    clasificados: 5,
    noClasificados: 8,
    descalificados: 0,
    responsable: 'SV Sofía Vargas',
    estado: 'En evaluación',
  },
  {
    id: '7',
    nombre: 'Robótica',
    nivel: 'Lego S',
    faseActual: 'Final',
    progreso: 100,
    clasificados: 10,
    noClasificados: 5,
    descalificados: 2,
    responsable: 'JR Juan Rojas',
    estado: 'Confirmado',
  },
  {
  id: '8',
  nombre: 'Matemáticas',
  nivel: 'Tercer Nivel',
  faseActual: 'Clasificatorio',
  progreso: 30,
  clasificados: 22,
  noClasificados: 15,
  descalificados: 0,
  responsable: 'DR Diego Ramírez',
  estado: 'En evaluación',
},
{
  id: '9',
  nombre: 'Física',
  nivel: '5to Secundaria',
  faseActual: 'Final',
  progreso: 100,
  clasificados: 9,
  noClasificados: 3,
  descalificados: 1,
  responsable: 'CQ Carlos Quispe',
  estado: 'Concluido',
},
{
  id: '10',
  nombre: 'Química',
  nivel: '4to Secundaria',
  faseActual: 'Clasificatorio',
  progreso: 80,
  clasificados: 14,
  noClasificados: 6,
  descalificados: 2,
  responsable: 'AR Ana Rodríguez',
  estado: 'En evaluación',
},
{
  id: '11',
  nombre: 'Biología',
  nivel: '6to Primaria',
  faseActual: 'Final',
  progreso: 95,
  clasificados: 11,
  noClasificados: 4,
  descalificados: 0,
  responsable: 'LM Luis Mamani',
  estado: 'Confirmado',
},
{
  id: '12',
  nombre: 'Informática',
  nivel: 'Jucumari',
  faseActual: 'Clasificatorio',
  progreso: 50,
  clasificados: 7,
  noClasificados: 9,
  descalificados: 1,
  responsable: 'PT Pedro Torrez',
  estado: 'En evaluación',
},
{
  id: '13',
  nombre: 'Astronomía - Astrofísica', // ⚠️ con espacios alrededor del guion
  nivel: '2do Secundaria',
  faseActual: 'Clasificatorio',
  progreso: 20,
  clasificados: 4,
  noClasificados: 10,
  descalificados: 0,
  responsable: 'SV Sofía Vargas',
  estado: 'Iniciado',
},
{
  id: '14',
  nombre: 'Robótica',
  nivel: 'Builders P',
  faseActual: 'Final',
  progreso: 100,
  clasificados: 6,
  noClasificados: 2,
  descalificados: 0,
  responsable: 'JR Juan Rojas',
  estado: 'Concluido',
},
{
  id: '15',
  nombre: 'Matemáticas',
  nivel: 'Sexto Nivel',
  faseActual: 'Final',
  progreso: 100,
  clasificados: 5,
  noClasificados: 3,
  descalificados: 1,
  responsable: 'MG María González',
  estado: 'Confirmado',
},
{
  id: '16',
  nombre: 'Informática',
  nivel: 'Bufo',
  faseActual: 'Clasificatorio',
  progreso: 65,
  clasificados: 10,
  noClasificados: 8,
  descalificados: 2,
  responsable: 'PT Pedro Torrez',
  estado: 'En evaluación',
},
{
  id: '17',
  nombre: 'Física',
  nivel: '1ro Secundaria',
  faseActual: 'Clasificatorio',
  progreso: 10,
  clasificados: 2,
  noClasificados: 18,
  descalificados: 0,
  responsable: 'CQ Carlos Quispe',
  estado: 'Iniciado',
},
{
  id: '18',
  nombre: 'Matemáticas',
  nivel: 'Segundo Nivel',
  faseActual: 'Clasificatorio',
  progreso: 40,
  clasificados: 18,
  noClasificados: 12,
  descalificados: 1,
  responsable: 'MG María González',
  estado: 'En evaluación',
},
{
  id: '19',
  nombre: 'Matemáticas',
  nivel: 'Cuarto Nivel',
  faseActual: 'Final',
  progreso: 90,
  clasificados: 7,
  noClasificados: 2,
  descalificados: 0,
  responsable: 'MG María González',
  estado: 'Confirmado',
},
{
  id: '20',
  nombre: 'Matemáticas',
  nivel: 'Quinto Nivel',
  faseActual: 'Clasificatorio',
  progreso: 25,
  clasificados: 5,
  noClasificados: 15,
  descalificados: 0,
  responsable: 'MG María González',
  estado: 'Iniciado',
},

{
  id: '21',
  nombre: 'Física',
  nivel: '2do Secundaria',
  faseActual: 'Clasificatorio',
  progreso: 55,
  clasificados: 13,
  noClasificados: 7,
  descalificados: 1,
  responsable: 'CQ Carlos Quispe',
  estado: 'En evaluación',
},
{
  id: '22',
  nombre: 'Física',
  nivel: '4to Secundaria',
  faseActual: 'Final',
  progreso: 100,
  clasificados: 10,
  noClasificados: 2,
  descalificados: 1,
  responsable: 'CQ Carlos Quispe',
  estado: 'Concluido',
},
{
  id: '23',
  nombre: 'Física',
  nivel: '6to Secundaria',
  faseActual: 'Clasificatorio',
  progreso: 15,
  clasificados: 3,
  noClasificados: 17,
  descalificados: 0,
  responsable: 'CQ Carlos Quispe',
  estado: 'Iniciado',
},

{
  id: '24',
  nombre: 'Biología',
  nivel: '3ro Primaria',
  faseActual: 'Clasificatorio',
  progreso: 35,
  clasificados: 9,
  noClasificados: 11,
  descalificados: 0,
  responsable: 'LM Luis Mamani',
  estado: 'En evaluación',
},
{
  id: '25',
  nombre: 'Biología',
  nivel: '1ro Secundaria',
  faseActual: 'Final',
  progreso: 100,
  clasificados: 8,
  noClasificados: 4,
  descalificados: 1,
  responsable: 'LM Luis Mamani',
  estado: 'Confirmado',
},
{
  id: '26',
  nombre: 'Biología',
  nivel: '4to Secundaria',
  faseActual: 'Clasificatorio',
  progreso: 70,
  clasificados: 12,
  noClasificados: 6,
  descalificados: 2,
  responsable: 'LM Luis Mamani',
  estado: 'En evaluación',
},

{
  id: '27',
  nombre: 'Informática',
  nivel: 'Guacamo',
  faseActual: 'Clasificatorio',
  progreso: 20,
  clasificados: 6,
  noClasificados: 14,
  descalificados: 0,
  responsable: 'PT Pedro Torrez',
  estado: 'Iniciado',
},
{
  id: '28',
  nombre: 'Informática',
  nivel: 'Guanaco',
  faseActual: 'Clasificatorio',
  progreso: 45,
  clasificados: 11,
  noClasificados: 9,
  descalificados: 1,
  responsable: 'PT Pedro Torrez',
  estado: 'En evaluación',
},
{
  id: '29',
  nombre: 'Informática',
  nivel: 'Londra',
  faseActual: 'Final',
  progreso: 100,
  clasificados: 9,
  noClasificados: 3,
  descalificados: 0,
  responsable: 'PT Pedro Torrez',
  estado: 'Concluido',
},

{
  id: '30',
  nombre: 'Robótica',
  nivel: 'Builders S',
  faseActual: 'Clasificatorio',
  progreso: 60,
  clasificados: 8,
  noClasificados: 4,
  descalificados: 1,
  responsable: 'JR Juan Rojas',
  estado: 'En evaluación',
},
{
  id: '31',
  nombre: 'Robótica',
  nivel: 'Lego P',
  faseActual: 'Final',
  progreso: 95,
  clasificados: 7,
  noClasificados: 2,
  descalificados: 0,
  responsable: 'JR Juan Rojas',
  estado: 'Confirmado',
},

{
  id: '32',
  nombre: 'Química',
  nivel: '3ro Secundaria',
  faseActual: 'Clasificatorio',
  progreso: 50,
  clasificados: 16,
  noClasificados: 8,
  descalificados: 2,
  responsable: 'AR Ana Rodríguez',
  estado: 'En evaluación',
},
{
  id: '33',
  nombre: 'Química',
  nivel: '5to Secundaria',
  faseActual: 'Final',
  progreso: 100,
  clasificados: 12,
  noClasificados: 5,
  descalificados: 1,
  responsable: 'AR Ana Rodríguez',
  estado: 'Concluido',
},
{
  id: '34',
  nombre: 'Química',
  nivel: '6to Secundaria',
  faseActual: 'Clasificatorio',
  progreso: 30,
  clasificados: 10,
  noClasificados: 12,
  descalificados: 0,
  responsable: 'AR Ana Rodríguez',
  estado: 'Iniciado',
},

{
  id: '35',
  nombre: 'Astronomía - Astrofísica',
  nivel: '5to Primaria',
  faseActual: 'Clasificatorio',
  progreso: 40,
  clasificados: 6,
  noClasificados: 9,
  descalificados: 1,
  responsable: 'SV Sofía Vargas',
  estado: 'En evaluación',

},


];

  return (
    <div className="p-6 max-w-7xl mx-auto">
      <h1 className="text-2xl font-bold mb-6">🧪 Control de Fases (Prueba)</h1>
      <ControlFasesTable areas={areas} rolUsuario="Administrador" />
    </div>
  );
}
